# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  trellis-project:
    site_title: "Trellis Project (DEVELOPMENT)"
    site_hosts:
      - canonical: trellis-project.local
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: jamespdoris@gmail.com
    multisite:
      enabled: false
    ssl:
      enabled: false
    cache:
      enabled: false
